bluez: Fix agent registration
They were causing tracebacks.

Agent registration failed: GDBus.Error:org.freedesktop.DBus.Python.AttributeError: Traceback (most recent call last):
  File "/usr/lib64/python3.10/site-packages/dbus/service.py", line 715, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/home/hadess/Projects/gnome-install/lib/python3.10/site-packages/dbusmock/mockobject.py", line 398, in <lambda>
    method = lambda self, *args, **kwargs: DBusMockObject.mock_method(
  File "/home/hadess/Projects/gnome-install/lib/python3.10/site-packages/dbusmock/mockobject.py", line 667, in mock_method
    return code(self, *args)
  File "/home/hadess/Projects/gnome-install/lib/python3.10/site-packages/dbusmock/templates/bluez5.py", line 49, in RegisterAgent
    if agent_path in manager.agent_paths:
AttributeError: 'DBusMockObject' object has no attribute 'agent_paths'