Give path and interface names to Disconnected signal
We certainly want to handle the Disconnected signal only if it comes
from the bus. We need to set path to DBUS_LOCAL_PATH and interface to
DBUS_LOCAL_INTERFACE. Failing to do so gives us one of the following
errors:

1) If our application's "Disconnected" signal has the same signature, it
will end up closing the application

2) If our application's "Disconnected" signal has a different signature,
it will give the folowing log on stderr:

Traceback (most recent call last):
  File "/usr/lib/python3.3/site-packages/dbus/connection.py", line 233, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/lib/python3.3/site-packages/gi/types.py", line 115, in function
    return info.invoke(*args, **kwargs)
TypeError: quit() takes exactly 1 argument (2 given)