Don't introspect None properties
Fix crash when a property value is None:

  TypeError: Don't know which D-Bus type to use to encode type "NoneType"
  
(regression from r164)